drop table VACANCIES;
CREATE table IF NOT EXISTS VACANCIES(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR (100) NOT NULL ,
  salary INTEGER NOT NULL ,
  experience VARCHAR (100) NOT NULL ,
  city VARCHAR(200) NOT NULL
);